name: ecb
channels:
  - pytorch
  - huggingface
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - anyio=3.2.1=py38h578d9bd_0
  - asgiref=3.3.4=pyhd8ed1ab_0
  - attrs=20.2.0=py_0
  - azure-cli=0.10.3=0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h7b6447c_1000
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=py38_0
  - cffi=1.14.3=py38he30daa8_0
  - chardet=3.0.4=py38_1003
  - click=8.0.1=py38h578d9bd_0
  - coverage=5.3=py38h7b6447c_0
  - cryptography=3.1.1=py38h1ba5d50_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - dataclasses=0.8=pyh6d0b6a4_7
  - fastapi=0.65.2=pyhd8ed1ab_0
  - filelock=3.0.12=pyhd3eb1b0_1
  - flake8=3.9.2=pyhd3eb1b0_0
  - h11=0.12.0=pyhd8ed1ab_0
  - h2=4.0.0=py38h578d9bd_3
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=0.13.6=pyhd8ed1ab_0
  - httpx=0.18.1=py38h578d9bd_1
  - huggingface_hub=0.0.10=py_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=68.1=h2531618_0
  - idna=2.10=py_0
  - importlib-metadata=3.10.0=py38h06a4308_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - iniconfig=1.1.1=py_0
  - intel-openmp=2021.2.0=h06a4308_610
  - jinja2=3.0.0=pyhd3eb1b0_0
  - joblib=1.0.1=pyhd3eb1b0_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libprotobuf=3.14.0=h8c45485_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libuv=1.40.0=h7b6447c_0
  - markupsafe=2.0.1=py38h27cfd23_0
  - mccabe=0.6.1=py38_1
  - mkl=2021.2.0=h06a4308_296
  - mkl-service=2.3.0=py38h27cfd23_1
  - mkl_fft=1.3.0=py38h42c9631_2
  - mkl_random=1.2.1=py38ha9443f7_2
  - more-itertools=8.5.0=py_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=hff7bd54_1
  - nltk=3.5=py_0
  - nodejs=14.8.0=hda19d22_0
  - numpy=1.20.2=py38h2d18471_0
  - numpy-base=1.20.2=py38hfae3a4d_0
  - openssl=1.1.1k=h7f98852_0
  - packaging=20.4=py_0
  - pip=21.1.2=py38h06a4308_0
  - pluggy=0.13.1=py38_0
  - protobuf=3.14.0=py38h2531618_1
  - py=1.9.0=py_0
  - pycodestyle=2.7.0=pyhd3eb1b0_0
  - pycparser=2.20=py_2
  - pydantic=1.8.2=py38h497a2fe_0
  - pyflakes=2.3.1=pyhd3eb1b0_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pysocks=1.7.1=py38_0
  - pytest-asyncio=0.15.1=pyhd8ed1ab_0
  - pytest-mock=3.3.1=py_0
  - python=3.8.10=h12debd9_8
  - python-multipart=0.0.5=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.9.0=py3.8_cuda10.2_cudnn7.6.5_0
  - readline=8.1=h27cfd23_0
  - regex=2021.4.4=py38h27cfd23_0
  - requests=2.24.0=py_0
  - rfc3986=1.5.0=pyhd8ed1ab_0
  - sacremoses=master=py_0
  - setuptools=52.0.0=py38h06a4308_0
  - six=1.15.0=py_0
  - sniffio=1.2.0=py38h578d9bd_1
  - sqlite=3.35.4=hdfb4753_0
  - starlette=0.14.2=pyhd8ed1ab_0
  - tk=8.6.10=hbc83047_0
  - tokenizers=0.10.3=py38_0
  - toml=0.10.1=py_0
  - tqdm=4.59.0=pyhd3eb1b0_1
  - transformers=4.6.1=py_0
  - typing-extensions=3.10.0.0=hd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - urllib3=1.25.11=py_0
  - uvicorn=0.14.0=py38h578d9bd_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - adal==1.2.7
    - azure-common==1.1.27
    - azure-core==1.15.0
    - azure-graphrbac==0.61.1
    - azure-mgmt-authorization==0.61.0
    - azure-mgmt-containerregistry==8.0.0
    - azure-mgmt-core==1.2.2
    - azure-mgmt-keyvault==9.0.0
    - azure-mgmt-resource==13.0.0
    - azure-mgmt-storage==11.2.0
    - azureml-core==1.31.0
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - contextlib2==0.6.0.post1
    - docker==4.4.4
    - isodate==0.6.0
    - jeepney==0.6.0
    - jmespath==0.10.0
    - jsonpickle==2.0.0
    - msrest==0.6.21
    - msrestazure==0.6.4
    - ndg-httpsclient==0.5.1
    - oauthlib==3.1.1
    - pathspec==0.8.1
    - pyasn1==0.4.8
    - pyjwt==2.1.0
    - pytest==6.2.4
    - pytest-order==1.0.0
    - python-dateutil==2.8.1
    - pytz==2021.1
    - requests-oauthlib==1.3.0
    - ruamel-yaml==0.17.4
    - ruamel-yaml-clib==0.2.2
    - secretstorage==3.3.1
    - websocket-client==1.1.0
prefix: /opt/anaconda3/envs/ecb
